# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentfulproxy < Formula
  desc "An experimental proxy for read access to contentful to save your API quota"
  homepage "https://github.com/foomo/contentfulproxy"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.2/contentfulproxy_0.1.2_darwin_amd64.tar.gz"
      sha256 "21b38be386da60e153cc348230f84d97ca0ea91fc67bdf70ad082bb0452fa6c7"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.2/contentfulproxy_0.1.2_linux_amd64.tar.gz"
      sha256 "9bb1489752c75026b042a9946f3e7cbfa0d2e4e190fb3ab880c1d8e0ab7aee8e"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  def caveats; <<~EOS
    contentfulproxy -webserver-address=$CONTENTFULPROXY_SERVER_ADDR
  EOS
  end
end
