# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentfulproxy < Formula
  desc "An experimental proxy for read access to contentful to save your API quota"
  homepage "https://github.com/foomo/contentfulproxy"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.6/contentfulproxy_0.1.6_darwin_amd64.tar.gz"
      sha256 "3a40d3436204db6200e7b3468f0e1eec2b40480fc0ecc8080a4188e43527fb83"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.6/contentfulproxy_0.1.6_linux_amd64.tar.gz"
      sha256 "c0349d5e1a8eb906b486b55adcd236bd9360de3bd6ac003d82299f00b0c6324b"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  def caveats; <<~EOS
    contentfulproxy -webserver-address=$CONTENTFULPROXY_SERVER_ADDR
  EOS
  end
end
