# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentfulproxy < Formula
  desc "An experimental proxy for read access to contentful to save your API quota"
  homepage "https://github.com/foomo/contentfulproxy"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.5/contentfulproxy_0.1.5_darwin_amd64.tar.gz"
      sha256 "a216b1049b154bcf5488659a9636d46c27567003e289406005050a3d7522674e"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulproxy/releases/download/v0.1.5/contentfulproxy_0.1.5_linux_amd64.tar.gz"
      sha256 "b1b4546eb97910a24f203b56e0c36a9ff4e1a5ebd8e14dcffe03a43e0af433d6"

      def install
        bin.install "contentfulproxy"
      end
    end
  end

  def caveats; <<~EOS
    contentfulproxy -webserver-address=$CONTENTFULPROXY_SERVER_ADDR
  EOS
  end
end
